"""empty message

Revision ID: c1346ac863ec
Revises: 7b81d5ed3672
Create Date: 2022-09-25 23:44:12.075283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1346ac863ec'
down_revision = '7b81d5ed3672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('owner', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'pokemon', 'user', ['owner'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pokemon', type_='foreignkey')
    op.drop_column('pokemon', 'owner')
    # ### end Alembic commands ###
